---
# tasks file for niftymist.baseline
- name: ensure ansible user is created
  user:
    name: "{{ baseline_ansible_user }}"
    state: present
    password: "{{ baseline_ansible_password }}"

- name: ensure ansible user has deployed ssh key
  authorized_key:
    user: "{{ baseline_ansible_user }}"
    state: present
    key: "{{ lookup('file', '/home/dmitchell/.ssh/ansible.pub') }}"

- name: ensure standard user is created
  user:
    name: "{{ baseline_standard_user }}"
    state: present
    password: "{{ baseline_standard_password }}"

- name: ensure ansible user has deployed ssh key
  authorized_key:
    user: "{{ baseline_standard_user }}"
    state: present
    key: "{{ lookup('file', '/home/dmitchell/.ssh/id_rsa.pub') }}"

- name: deploy ansible sudoers files
  template:
    src: nopasswd.j2
    dest: "/etc/sudoers.d/{{ baseline_ansible_user }}"
    owner: root
    group: root
    mode: 0644

- name: deploy standard sudoers files
  template:
    src: passwd.j2
    dest: "/etc/sudoers.d/{{ baseline_standard_user }}"
    owner: root
    group: root
    mode: 0644