---
# tasks file for niftymist.baseline
- name: install baseline packages
  package:
    name: "{{ baseline_packages }}"
    state: present
  register: package_install
  ignore_errors: true

- name: update apt cache if needed
  apt:
    update_cache: true
  when: package_install.failed

- name: install baseline packages if failed
  package:
    name: "{{ baseline_packages }}"
    state: present
  when: package_install.failed

- name: ensure ansible user is created
  user:
    name: "{{ baseline_ansible_user }}"
    state: present
    password: "{{ baseline_ansible_password }}"
  no_log: true

- name: ensure ansible user has deployed ssh key
  authorized_key:
    user: "{{ baseline_ansible_user }}"
    state: present
    key: "{{ baseline_ansible_user_pub_key_url }}"

- name: ensure standard user is created
  user:
    name: "{{ baseline_standard_user }}"
    state: present
    shell: /bin/zsh
    password: "{{ baseline_standard_password }}"
  no_log: true

- name: ensure ansible user has deployed ssh key
  authorized_key:
    user: "{{ baseline_standard_user }}"
    state: present
    key: "{{ baseline_ansible_user_pub_key_url }}"

- name: deploy ansible sudoers file
  template:
    src: nopasswd.j2
    dest: "/etc/sudoers.d/{{ baseline_ansible_user }}"
    owner: root
    group: root
    mode: 0644

- name: deploy standard sudoers file
  template:
    src: passwd.j2
    dest: "/etc/sudoers.d/{{ baseline_standard_user }}"
    owner: root
    group: root
    mode: 0644
