---
# tasks file for niftymist.baseline
- name: update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: install baseline packages
  ansible.builtin.package:
    name: "{{ baseline_packages }}"
    state: present
  register: package_install
  ignore_errors: true

- name: install baseline packages if failed
  ansible.builtin.package:
    name: "{{ baseline_packages }}"
    state: present
  when: package_install.failed

- name: create groups
  ansible.builtin.group:
    state: present
    name: "{{ item }}"
  with_items: "{{ baseline_groups }}"
  when: baseline_groups is defined

- name: ensure ansible user is created
  ansible.builtin.user:
    name: "{{ baseline_ansible_user }}"
    state: present
    password: "{{ baseline_ansible_password | default('changeme') }}"
  no_log: true

- name: ensure ansible user has deployed ssh key
  ansible.builtin.authorized_key:
    user: "{{ baseline_ansible_user }}"
    state: present
    key: "{{ baseline_ansible_user_pub_key_url | default(omit) }}"
  when: baseline_ansible_user_pub_key_url is defined

- name: ensure standard user is created
  ansible.builtin.user:
    name: "{{ baseline_standard_user }}"
    state: present
    shell: /bin/bash
    password: "{{ baseline_standard_password | default('changeme') }}"
  no_log: true
  when: baseline_standard_user is defined

- name: ensure ansible user has deployed ssh key
  ansible.builtin.authorized_key:
    user: "{{ baseline_standard_user }}"
    state: present
    key: "{{ baseline_ansible_user_pub_key_url | default(omit) }}"
  when: baseline_ansible_user_pub_key_url is defined

- name: deploy ansible sudoers file
  ansible.builtin.template:
    src: nopasswd.j2
    dest: "/etc/sudoers.d/{{ baseline_ansible_user }}"
    owner: root
    group: root
    mode: 0644

- name: deploy standard sudoers file
  ansible.builtin.template:
    src: passwd.j2
    dest: "/etc/sudoers.d/{{ baseline_standard_user }}"
    owner: root
    group: root
    mode: 0644

  when: baseline_standard_user is defined

- name: deploy /etc/motd
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: set roots bash prompt
  ansible.builtin.template:
    src: root-bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0544
