---
# tasks file for niftymist.baseline
- name: install zsh
  package:
    name: zsh
    state: present

- name: ensure ansible user is created
  user:
    name: "{{ baseline_ansible_user }}"
    state: present
    password: "{{ baseline_ansible_password }}"

- name: ensure ansible user has deployed ssh key
  authorized_key:
    user: "{{ baseline_ansible_user }}"
    state: present
    key: "{{ lookup('file', '/home/dmitchell/.ssh/id_ed25519_ansible.pub') }}"

- name: ensure standard user is created
  user:
    name: "{{ baseline_standard_user }}"
    state: present
    shell: /bin/zsh
    password: "{{ baseline_standard_password }}"

- name: ensure ansible user has deployed ssh key
  authorized_key:
    user: "{{ baseline_standard_user }}"
    state: present
    key: "{{ lookup('file', '/home/dmitchell/.ssh/id_ed25519.pub') }}"

- name: deploy ansible sudoers files
  template:
    src: nopasswd.j2
    dest: "/etc/sudoers.d/{{ baseline_ansible_user }}"
    owner: root
    group: root
    mode: 0644

- name: deploy standard sudoers files
  template:
    src: passwd.j2
    dest: "/etc/sudoers.d/{{ baseline_standard_user }}"
    owner: root
    group: root
    mode: 0644

- name: get ohmyzsh install script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "/home/{{ baseline_standard_user }}/install.sh"
    mode: 0777
    owner: "{{ baseline_standard_user }}"
    group: "{{ baseline_standard_user }}"

#- name: install ohmyzsh
#  command: "/home/{{ baseline_standard_user }}/install.sh"
#  become: yes
#  become_method: su
#  become_user: "{{ baseline_standard_user }}"