---
- name: Converge
  hosts: all
  become: true
  vars:
    baseline_ansible_user: ansible
    # yamllint disable-line rule:line-length
    baseline_ansible_password: $6$u5vO2.ctI8dhAC2w$cCKzrf1hJCDiVla.FoTJlwv2oticvpd54OTAdSBAuaPqEfMgOGAOpkdb3cxfHE3T5nyzGEtlFDfCw5JZQmiOp.
    baseline_standard_user: skywalker
    # yamllint disable-line rule:line-length
    baseline_standard_password: $6$u5vO2.ctI8dhAC2w$cCKzrf1hJCDiVla.FoTJlwv2oticvpd54OTAdSBAuaPqEfMgOGAOpkdb3cxfHE3T5nyzGEtlFDfCw5JZQmiOp.
    baseline_ansible_user_pub_key_url: "https://gist.githubusercontent.com/NiftyMist/55f4453467dbab4ee8331d071b56c4b4/raw/ca79e4a277908f39d7ca5967f50392d0ee4fd4fc/ansible.pub"
    baseline_standard_user_pub_key_url: "https://gist.githubusercontent.com/NiftyMist/b693ea48cbb55b7802b84e0227386a33/raw/a31834ac0b5e1641a0d091fecaf71debaf15dbdd/skywalker.pub"
  tasks:
    - name: "Include niftymist.baseline"
      include_role:
        name: "niftymist.baseline"
