---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: niftymist-baseline
    image: geerlingguy/docker-ubuntu2004-ansible
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callback: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
