---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - uses: gofrolist/molecule-action@v2
