on: push

jobs:
  molecule:
    runs-on: geerlingguy/docker-ubuntu2004-ansible
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2